spring:
  security:
    # 如果配置了 UserDetailsService Beam，该配置失效
    user:
      name: DawnSilverGravel
      password: DawnSilverGravel
      roles:
        - DawnSilverGravel
        - ADMIN
        - USER
