server:
  port: 8900
spring:
  redis:
    port: 6379
    host: 192.168.107.141
    password: DawnSilverGravel
    database: 0
    lettuce:
      pool:
        # 最大连接数 默认为8
        max-active: 10
        # 最大阻塞等待时间，负数表示没限制
        max-wait: -1
        # 最大空闲默认 8
        max-idle: 10
        # 最小空闲
        min-idle: 0
    # 连接超时时间
    timeout: 60000