spring:
  datasource:
    url: jdbc:h2:file:./data/gravel
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
  jpa:
    database-platform: H2
#  aop:
#    auto: true
#    proxy-target-class: false